# Generated by Django 2.0.6 on 2020-11-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Organizer', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Организаторы'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Lessons', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Students', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Teachers', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Organizer', verbose_name='Организатор'),
        ),
    ]
