# Generated by Django 2.0.6 on 2020-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201106_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='title',
            field=models.CharField(default='Theme', max_length=300, verbose_name='Тема занятия'),
        ),
    ]
