# Generated by Django 2.2 on 2020-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_subjects_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='groups',
            field=models.ManyToManyField(related_name='teacher_groups', to='reviews.Groups', verbose_name='Группы'),
        ),
    ]
