# Generated by Django 2.2 on 2020-12-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_teachers_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(related_name='teacher_subjects', to='reviews.Subjects', verbose_name='Предметы'),
        ),
    ]
