# Generated by Django 2.2 on 2020-12-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20201213_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='rating',
        ),
        migrations.AddField(
            model_name='answers',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Reviews', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
