# Generated by Django 2.2 on 2020-12-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_answers_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='student',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='teacher',
        ),
        migrations.AddField(
            model_name='reviews',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Students', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Teachers', verbose_name='Преподаватель'),
        ),
    ]
