# Generated by Django 2.2 on 2020-12-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20201213_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Subjects', verbose_name='Предмет'),
        ),
    ]
