# Generated by Django 2.2 on 2020-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20201214_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='сriterions',
        ),
        migrations.AddField(
            model_name='answers',
            name='availability',
            field=models.PositiveIntegerField(default=0, verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='answers',
            name='fascination',
            field=models.PositiveIntegerField(default=0, verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='answers',
            name='interest',
            field=models.PositiveIntegerField(default=0, verbose_name='Заинтересованность'),
        ),
        migrations.AddField(
            model_name='answers',
            name='novelty',
            field=models.PositiveIntegerField(default=0, verbose_name='Новизна'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='answers',
            name='сomplexity',
            field=models.PositiveIntegerField(default=0, verbose_name='Сложность'),
        ),
    ]
