# Generated by Django 2.2 on 2020-12-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20201215_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Students', verbose_name='Студент'),
        ),
    ]
