# Generated by Django 2.2 on 2020-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_answers_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=60, null=True, verbose_name='E-mail'),
        ),
    ]
