# Generated by Django 2.2 on 2020-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='teacher_groups', to='reviews.Groups', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='teacher_subjects', to='reviews.Subjects', verbose_name='Предметы'),
        ),
    ]
